var terms_enGB = new Array(19);

for(var i = 0; i < 19; i++)
	terms_enGB[i] = new Array();


terms_enGB[0][0] = "Terms of Use";
terms_enGB[0][1] = "Please, read the terms of use carefully:";
terms_enGB[0][2] = "PAT2Math's Service Terms:";
terms_enGB[0][3] = "back";

terms_enGB[1][0] = '1. User relationship with PAT2Math';
terms_enGB[1][1] = '1.1. The use of PAT2Math\'s products, services, and web sites (collectively referred to as "Services" in this document and excluding any services provided to the user by PAT2Math pursuant to a separate written agreement) by the user is subject to the terms of a contract between the user and PAT2Math. "PAT2Math" stands for "Personal Affective Tutor to Math" and is being developed by a team of researchers in Artificial Intelligence applied to the Education of the Interdisciplinary Program of Applied Computation of UNISINOS in São Leopoldo, under the coordination of Prof. Patrícia A. Jaques Maillard. This document explains how the contract is made and presents its terms.';
terms_enGB[1][2] = '1.2. Unless otherwise agreed in writing by PAT2Math, the user agreement with PAT2Math shall always include, at a minimum, the terms and conditions set forth in this document. Such terms are called "Universal Terms".';
terms_enGB[1][3] = '1.3. The user agreement with PAT2Math shall also include the terms of any Legal Notices applicable to the Services, in addition to the Universal Terms. All such terms are hereinafter referred to as "Additional Terms". In those cases where Additional Terms apply to a Service, such terms will be available to the user to read in or through the use of that Service.';
terms_enGB[1][4] = '1.4. The Universal Terms, together with the Additional Terms, form a legal agreement between the user and PAT2Math regarding his use of the Services. It is important that the user read them carefully. Collectively, this agreement is called "Terms".';
terms_enGB[1][5] = '1.5. In the event that there is any contradiction between what the Additional Terms indicate and what the Universal Terms indicate, the Additional Terms shall prevail in relation to that Service.';

terms_enGB[2][0] = '2. Acceptance of Terms';
terms_enGB[2][1] = '2.1. In order to use the Services, the user must first agree to the Terms. The user may not use the Services if he does not accept the Terms.';
terms_enGB[2][2] = '2.2. The user may accept the Terms: (A) by clicking to accept or agree to the Terms, if such option is made available by PAT2Math in the user interface for any Service; or (B) effectively using the Services. In that case, the user understands and agree that PAT2Math will treat his use of the Services as acceptance of the Terms from that moment on.';
terms_enGB[2][3] = '2.3. The user may not use the Services or accept the Terms if: (a) is not of legal age to enter into a legally binding agreement with PAT2Math; or (b) is a person with restrictions on the receipt of services imposed by the laws of Brazil or other countries, including the country in which the user resides or from which they use the Services.';
terms_enGB[2][4] = '2.4. Before continuing, the user should print or save a local copy of the Universal Terms in his records.';

terms_enGB[3][0] = '3. Provision of Services by PAT2Math';
terms_enGB[3][1] = '3.1. PAT2Math is constantly innovating to be able to offer the best possible experience to its users. The user acknowledge and agree that the form and nature of the Services provided by PAT2Math may change from time to time without notice to the user.';
terms_enGB[3][2] = '3.2. As part of this constant innovation, the user acknowledges and agrees that PAT2Math may, in its sole discretion, cease (permanently or temporarily) to provide the Services (or any functionality of the Services) to users in general without prior notice. The user may not use the Services at any time. The user do not need to specifically inform PAT2Math when he stops using the Services.';
terms_enGB[3][3] = '3.3. The user acknowledge and agree that if PAT2Math deactivates his account, he may be prevented from accessing the Services, account details or any files or other content in the account.';

terms_enGB[4][0] = '4. Use of the Services by the user';
terms_enGB[4][1] = '4.1. To access certain Services, the user may be required to provide personal information (such as identification or contact details on social networks such as Facebook, LinkedIn, and so on) as part of the registration process for the Service or as part of continued use of the Services by the user. The user agrees that the registration information he provides to PAT2Math will always be accurate, correct and current.';
terms_enGB[4][2] = '4.2. The user agrees to use the Services only for the purposes permitted: (a) by the Terms; and (b) any generally accepted laws, regulations or practices or guidelines in the relevant jurisdictions (including all laws regarding the export of data or software to and from Brazil or other relevant countries).';
terms_enGB[4][3] = '4.3. The user agrees not to access (or attempt to access) any of the Services by any means other than through the interface provided by PAT2Math, unless he is specifically authorized to do so in a separate agreement with PAT2Math. The user specifically agrees not to access (or attempt to access) any of the Services through automated means (including use of scripts or web crawlers), as well as ensure to comply with the instructions set forth in all * .txt files presented in the Services.';
terms_enGB[4][4] = '4.4. The user agrees not to participate in any activity that interferes with or interrupts the operation of the Services (or servers and networks connected to the Services).';
terms_enGB[4][5] = '4.5. Unless specifically authorized by a separate agreement with PAT2Math, the user agrees not to reproduce, duplicate, copy, sell, market or resell the Services for any purpose.';
terms_enGB[4][6] = '4.6. The user agrees that he will be solely responsible (and that PAT2Math has no liability to the user or any third party) for any breach of his obligations with respect to the Terms and the consequences (including any loss or damage that PAT2Math may suffer) resulting from such non-compliance.';

terms_enGB[5][0] = '5. Account security and user passwords';
terms_enGB[5][1] = '5.1. The user agrees and understands that he will be responsible for maintaining the confidentiality of the passwords associated with any account he uses to access the Services.';
terms_enGB[5][2] = '5.2. Thus, the user agree that he will be solely responsible to PAT2Math for all activities that occur in his account.';
terms_enGB[5][3] = '5.3. If aware of any unauthorized use of his password or account, the user agrees to immediately notify PAT2Math at pat2math@gmail.com.';

terms_enGB[6][0] = '6. Content in the Services';
terms_enGB[6][1] = '6.1. The user understands that full responsibility for all information (such as data files, written text, computer software, music, audio files or other sounds, photographs, videos or other images) that he may have access to as part of the Services, or through the use thereof, is the person who gave rise to such content. All of this information is called "Content."';
terms_enGB[6][2] = '6.2  The user should be aware that the Content submitted to him as part of the Services, including, without limitation, advertisements in the Services and Content sponsored by the Services, may be protected by intellectual property rights owned by the advertisers or partners providing such Content to PAT2Math (or other persons or companies on his behalf). The user may not modify, rent, lease, loan, sell, distribute or create derivative works based on this Content (in whole or in part), unless specifically authorized to do so through a separate agreement, by PAT2Math or by the owners of such Content.';
terms_enGB[6][3] = '6.3. PAT2Math reserves the right (but has no obligation) to pre-screen, review, mark, filter, modify, refuse or remove any or all Content from any Service. For some of the Services, PAT2Math may provide tools for filtering explicit sexual content.';
terms_enGB[6][4] = '6.4. The user understands that, by using the Services, he may be exposed to Content that he may find offensive, indecent or objectionable and that in this regard uses the Services at his own risk.';
terms_enGB[6][5] = '6.5. The user agrees that he will be solely responsible (and that PAT2Math has no liability to the user or any third party) for any Content he creates, transmit or view while using the Services and for the consequences of his actions (including any loss or damage that PAT2Math may suffer) as a result.';

terms_enGB[7][0] = '7. Property Rights';
terms_enGB[7][1] = '7.1. The user acknowledges and agrees that PAT2Math (or PAT2Math licensors) owns all legal rights, titles and interests in respect of the Services, including any intellectual property rights that subsist on the Services (whether or not those rights are registered, and in any part of the world where these rights may exist). In addition, the user acknowledges that the Services may contain information designated as confidential by PAT2Math and will not disclose such information without the prior written consent of PAT2Math.';
terms_enGB[7][2] = '7.2. Unless the user has agreed in writing otherwise with PAT2Math, nothing in the Terms gives him the right to use any of the trademarks, trade marks, service marks, logos, domain names, and other special brand features of PAT2Math.';
terms_enGB[7][3] = '7.3. If granted an explicit right to use any of these trademark features through a separate written agreement with PAT2Math, the user agrees that use of these features will be done in accordance with such agreement, with any clauses applicable to the Terms and the guidelines for use of the PAT2Math trademark features as may be periodically updated.';
terms_enGB[7][4] = '7.4. With the exception of the limited license referred to in Section 1.1, PAT2Math acknowledges and agrees that it does not obtain any right, title or participation of the user (or its licensors) under these Terms in respect of any Content that the user may submit, publish, transmit or display on or through the Services, including any intellectual property rights that subsist in that Content (whether or not those rights are registered, and in any part of the world where such rights may exist). Unless agreed in writing otherwise with PAT2Math, the user agrees that he is responsible for protecting and enforcing those rights and that PAT2Math has no obligation to do so on his behalf.';
terms_enGB[7][5] = '7.5. The user agrees that will not remove, obscure, or alter any proprietary rights notices (including copyright and trademark notices) that may be posted or contained in the Services.';
terms_enGB[7][6] = '7.6. Unless expressly authorized in writing by PAT2Math to do so, the user agrees that in using the Services, he will not use any trademark, service mark, trademark, logo of any company or organization in any way that is likely or intended to cause confusion about the owner or authorized user of such marks, names or logos.';

terms_enGB[8][0] = '8. PAT2Math License';
terms_enGB[8][1] = '8.1. PAT2Math grants the user a personal, international, royalty-free, non-assignable and non-exclusive license to use the software provided to the user by PAT2Math as part of the services provided to the user by PAT2Math (referred to as "Software" below). This license is for the sole purpose of allowing the user to use the benefits of the Services as provided by PAT2Math in the manner permitted by the Terms.';
terms_enGB[8][2] = '8.2. The user may not (and may not allow anyone else) copy, modify, create a derivative work of, reverse engineer, decompile, or otherwise attempt to extract the source code of the Software or any part thereof, unless expressly permitted or provided by law, or that the user has been specifically authorized to do so by PAT2Math, in writing.';
terms_enGB[8][3] = '8.3. Unless PAT2Math has given the user specific written permission to do so, he may not assign (or grant a sub-license of) his rights to use the Software, grant a warranty relating to his rights of use of the Software or otherwise transfer any portion of his rights to use the Software.';
terms_enGB[8][4] = '8.4. PAT2Math reserves the right to exclude the user\'s usage history when it has not accessed the system for more than 3 months.';

terms_enGB[9][0] = '9. User Content License';
terms_enGB[9][1] = '9.1. The user retains copyright and any other rights that he already has in relation to the submited Content, post or display on or through the Services. By submitting, posting or displaying content, the user grant PAT2Math an irrevocable, perpetual, worldwide, royalty-free, non-exclusive license to reproduce, adapt, modify, translate, publish, publicly distribute, publicly display, and distribute any Content that the user sends, posts or displays on or through the Services. This license is for the sole purpose of allowing PAT2Math to submit, distribute and promote the Services and may be revoked for certain Services as defined in the Additional Terms of those Services.';
terms_enGB[9][2] = '9.2. The user agrees that this license includes the right of PAT2Math to make such Content available to other companies, organizations or individuals with whom PAT2Math has relationships for the provision of licensed services and for the use of such Content related to the provision of those services.';
terms_enGB[9][3] = '9.3. The user understands that PAT2Math, in performing the technical steps necessary to provide the Services to our users, may transmit or distribute his Content through various public networks and various data media; and (b) make any necessary changes to User Content to adjust and adapt such Content to the technical requirements for connecting networks, devices, services, or media. The user agree that this license will allow PAT2Math to perform such actions.';
terms_enGB[9][4] = '9.4. The user confirms and warrants to PAT2Math that he has all the rights, powers and authority necessary to grant the aforementioned license.';

terms_enGB[10][0] = '10. Software Updates';
terms_enGB[10][1] = '10.1. Software used by the user may occasionally automatically download and install PAT2Math updates. These updates are designed to improve, refine, and develop the Services and may be presented in the form of bug fixes, enhanced functions, new software modules, and completely new versions. The user agrees to receive such updates (and allow PAT2Math to provide him) as part of his use of the Services.';

terms_enGB[11][0] = '11. End of user relationship with PAT2Math';
terms_enGB[11][1] = '11.1. The Terms will continue to apply until terminated by the user or PAT2Math as set forth below.';
terms_enGB[11][2] = '11.2. If the user wish to terminate his agreement with PAT2Math, he may do so by notifying PAT2Math at any time and (b) by terminating the accounts for all Services he uses, if such option is made available by PAT2Math. The notice must be sent by the user, in writing, to the PAT2Math address indicated at the beginning of these Terms.';
terms_enGB[11][3] = '11.3. PAT2Math may at any time terminate the agreement with the user if: (A) the user have breached any provision of the Terms (or has acted in a way that clearly indicates that the user does not intend or can not abide by the Terms\' clauses); or (B) such is required by PAT2Math by law (for example, where the provision of the Services to the user is or becomes illegal); or (C) the partner with whom PAT2Math offered the Services to the user has terminated the relationship with PAT2Math or has ceased to offer the Services to the user; or (D) PAT2Math is in the process of transition to a situation where it no longer provides the Services to users in the country in which the user is a resident or from which uses the Services; or (E) the provision of the Services to the user by PAT2Math is no longer, in PAT2Math\'s opinion, commercially viable. (F) the user fails to access the system for 3 months.';
terms_enGB[11][4] = '11.4. Nothing in this Section shall affect the rights of PAT2Math relating to the provision of Services pursuant to Section 3 of the Terms.';
terms_enGB[11][5] = '11.5. When these Terms are terminated, all rights, obligations and liabilities that the user or PAT2Math have benefited from, have been subject to (or have accrued as long as the Terms have been in force) or that must expressly remain in force indefinitely shall be affected by that resolution, and the provisions of paragraph 18.6 shall continue to apply to such rights, obligations and liabilities indefinitely.';

terms_enGB[12][0] = '12. DISCLAIMER OF WARRANTIES';
terms_enGB[12][1] = '12.1. NOTHING IN THESE TERMS, INCLUDING SECTIONS 12 AND 13, SHALL EXCLUDE OR LIMIT THE RESPONSIBILITY OR WARRANTY OF PAT2MATH FOR LOSSES WHICH CAN NOT BE LEGALLY EXCLUDED OR LIMITED BY APPLICABLE LAW. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR CONDITIONS OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR LOSS OR DAMAGE CAUSED BY NEGLIGENCE, BREACH OF CONTRACT OR BREACH OF IMPLIED TERMS, OR INCIDENTAL AND CONSEQUENTIAL DAMAGES. THEREFORE, ONLY THE LIMITATIONS WHICH ARE PERMITTED BY LAW IN THE USER\'S JURISDICTION WILL APPLY TO HIM, AND OUR LIABILITY LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.';
terms_enGB[12][2] = '12.2. THE USER EXPRESSLY UNDERSTAND AND AGREE THAT THE USE OF THE SERVICES IS AT HIS OWN RISK AND THAT THE SERVICES ARE PROVIDED "AS IS" AND "ACCORDING TO AVAILABILITY".';
terms_enGB[12][3] = '12.3. SPECIFICALLY, PAT2MATH, ITS SUBSIDIARIES AND AFFILIATES AND LICENSORS DO NOT WARRANT THAT: (A) THE USE OF THE SERVICES WILL MEET THE USER\'S REQUIREMENTS; (B) THE USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE AND ERROR FREE; (C) ANY INFORMATION OBTAINED BY THE USER THROUGH THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE; AND (D) DEFECTS IN THE OPERATION OR FUNCTIONALITY OF ANY SOFTWARE PROVIDED TO THE USER AS PART OF THE SERVICES WILL BE CORRECTED.';
terms_enGB[12][4] = '12.4. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE SERVICES IS OBTAINED AT THE USER\'S OWN RISK AND THAT THE USER WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO THE SYSTEM OF HIS COMPUTER OR ANY OTHER DEVICE, OR LOSS OF DATA THAT ACKNOWLEDGES RESULT OF DOWNLOADING ANY MATERIAL.';
terms_enGB[12][5] = '12.5. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY THE PAT2MATH USER, OR THROUGH THESE, SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS.';
terms_enGB[12][6] = '12.6. PAT2MATH STILL EXPRESSLY DISCLAIMS ALL RESPONSIBILITIES, WARRANTIES OR CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.';

terms_enGB[13][0] = '13. LIMITATION OF LIABILITY';
terms_enGB[13][1] = '13.1. SUBJECT TO THE GENERAL CLAUSES MENTIONED IN PARAGRAPH 12.1 ABOVE, THE USER ACKNOWLEDGE AND AGREE THAT PAT2MATH, ITS SUBSIDIARIES AND AFFILIATES, AND ITS LICENSORS AND PARTNERS SHALL NOT BE LIABLE TO THE USER FOR: (A) ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY, INCURRED BY THE USER, CAUSED AND UNDER ANY THEORY OF LIABILITY. THIS WILL INCLUDE, BUT NOT LIMITED TO, ANY LOSS OF PROFITS (INCURRED DIRECTLY OR INDIRECTLY), ANY LOSS RELATED TO GOOD FAITH OR COMMERCIAL REPUTATION, ANY LOSS OF DATA THAT THE USER MAY SUFFER, COSTS OF ACQUISITION OF GOODS OR SERVICES OR ANOTHER INTANGIBLE LOSS; (B) ANY LOSS OR DAMAGE THAT THE USER MAY INCUR, INCLUDING, BUT NOT LIMITED TO, LOSS OR DAMAGES ARISING OUT OF: a. ANY EXPECTATION OF THE USER AS TO THE INTEGRITY, ACCURACY OR EXISTENCE OF ANY ADVERTISING, OR RESULTING FROM ANY RELATIONSHIP OR TRANSACTION CARRIED OUT WITH ANY ADVERTISER, SPONSOR OR PARTNER WHOSE ADVERTISEMENT APPEARS IN THE SERVICES; B. ANY CHANGES THAT PAT2MATH MAY MAKE TO THE SERVICES, OR FOR ANY PERMANENT OR TEMPORARY CESSATION OF THE SUPPLY OF THE SERVICES (OR ANY FUNCTIONALITY IN THE OWN SERVICES); w. THE DISPOSAL, CORRUPTION OR INABILITY TO STORE ANY CONTENT OR OTHER DATA OF COMMUNICATIONS HELD OR TRANSMITTED BY OR THROUGH THE USE OF THE SERVICES BY THE USER; d. THE FAILURE TO PROVIDE PAT2MATH, BY THE USER, OF CORRECT INFORMATION CONCERNING THE ACCOUNT; and. NO USER MAINTENANCE, SECURITY AND CONFIDENTIALITY OF THE DETAILS OF HIS ACCOUNT AND PASSWORD.';
terms_enGB[13][2] = '13.2. THE LIMITATIONS OF LIABILITY OF PAT2MATH BEFORE THE USER, REFERRED TO IN PARAGRAPH 13.1 ABOVE, SHALL APPLY REGARDLESS OF WHETHER PAT2MATH HAS BEEN ADVISED OF, OR EVEN THAT THE USER SHOULD BE KNOWN ABOUT THE POSSIBILITY OF SUCH LOSSES.';

terms_enGB[14][0] = '14. Copyright and Trademark Policies';
terms_enGB[14][1] = '14.1. It is PAT2Math\'s policy to respond to notices of alleged copyright infringement under applicable international intellectual property law, as well as terminate the accounts of repeat infringers.';

terms_enGB[15][0] = '15. Advertisements';
terms_enGB[15][1] = '15.1. Some of the Services are maintained by revenue from advertising and may display ads and promotions. Such advertisements may be contextual to the content of the information stored in the Services, searches made through the Services or other information.';
terms_enGB[15][2] = '15.2. The manner, manner and extent of PAT2Math advertising in the Services is subject to change without notice to the user.';
terms_enGB[15][3] = '15.3. Considering PAT2Math\'s granting of access to and use of the Services, the user agree to the possibility that PAT2Math will place such notices on the Services.';

terms_enGB[16][0] = '16. Other contents';
terms_enGB[16][1] = '16.1. The Services may include hyperlinks to other sites, content, or web resources. PAT2Math may have no control over any sites or web resources provided by companies or individuals other than PAT2Math.';
terms_enGB[16][2] = '16.2. The user acknowledges and agrees that PAT2Math is not responsible for the availability of any such external sites or resources and does not endorse any advertisement, product or other material available or originated from such web sites and resources.';
terms_enGB[16][3] = '16.3. the user acknowledges and agrees that PAT2Math is not liable for any loss or damage that he may incur as a result of the availability of such external sites or resources, or as a result of any expectation expected by the user in connection with the completeness, accuracy or existence of any advertisements, products or other materials present or available from such sites or web resources.';

terms_enGB[17][0] = '17. Changes to Terms';
terms_enGB[17][1] = '17.1. PAT2Math may periodically change the Universal Terms or Additional Terms.';
terms_enGB[17][2] = '17.2. The user understands and agrees that if he uses the Services after the date of amendment of the Universal Terms or Additional Terms, PAT2Math will treat such use as an acceptance of the updated Universal Terms or Additional Terms.';

terms_enGB[18][0] = '18. General legal terms';
terms_enGB[18][1] = '18.1. Occasionally, during the use of the Services, the user may (as a result of or through the use of the Services) use a service, download a software component or purchase goods provided by another person or company. The use of such services, software or goods by the user may be subject to separate terms between the user and the company or person in question. In this case, the Terms do not affect the legal relationship of the user with such companies or individuals.';
terms_enGB[18][2] = '18.2. The Terms constitute the entire agreement between the user and PAT2Math and govern the use of the Services (excluding any services that may be provided by PAT2Math under a separate written agreement), completely replacing any prior agreements between the user and the PAT2Math in relation to the Services.';
terms_enGB[18][3] = '18.3. The user agrees that PAT2Math may send him notices, including those regarding changes to the Terms, by email, letter or publications on the Services.';
terms_enGB[18][4] = '18.4. The user agrees that if PAT2Math does not exercise or use any legal right or recognized right contained in the Terms (or to which PAT2Math is entitled under any applicable law), this shall not be considered as a formal waiver of PAT2Math\'s rights, and such rights shall remain available for all due effects.';
terms_enGB[18][5] = '18.5. If any court having jurisdiction to decide on this issue determines that any provision of these Terms is invalid, such provision shall be removed from the Terms without affecting the validity of the remaining Terms. The remaining terms of the Terms will continue to be valid and enforceable.';
terms_enGB[18][6] = '18.6. The Terms, and the relationship between the user and PAT2Math under the Terms, shall be governed by the laws of the State of Rio Grande do Sul, regardless of the conflict of law clauses. The user and PAT2Math agree to submit to the exclusive jurisdiction of the courts located in the City of São Leopoldo, Rio Grande do Sul, the resolution of any legal issues arising from the Terms. Notwithstanding the foregoing,  agree that PAT2Math may also file injunctive relief (or equivalent type of urgent legal compensation) in any jurisdiction.';
