var terms_ptBR = new Array(19);

for(var i = 0; i < 19; i++)
	terms_ptBR[i] = new Array();


terms_ptBR[0][0] = "Termos de Uso";
terms_ptBR[0][1] = "Por favor, leia com atenção os termos de uso:";
terms_ptBR[0][2] = "Termos de Serviço do PAT2Math:";
terms_ptBR[0][3] = "voltar";

terms_ptBR[1][0] = '1. Relação do usuário com o PAT2Math';
terms_ptBR[1][1] = '1.1. O uso de produtos, software, serviços e sites da web do PAT2Math (denominados coletivamente "Serviços" neste documento e excluindo quaisquer serviços fornecidos ao usuário pelo PAT2Math de acordo com um contrato por escrito separado) por parte do usuário está sujeito aos termos de um contrato entre o usuário e o PAT2Math. "PAT2Math" significa "Personal Affective Tutor to Math" (Tutor individual afetivo para matemática) e está sendo desenvolvido por uma equipe de pesquisadores em Inteligência Artificial aplicada à Educação do Programa Interdisciplinar de Pós-graduação em Computação Aplicada da UNISINOS, em São Leopoldo, sob a coordenação da Profa. Patrícia A. Jaques Maillard. Este documento explica como é constituído o contrato e apresenta seus termos.';
terms_ptBR[1][2] = '1.2. Exceto se acordado de outra forma por escrito pelo PAT2Math, o contrato do usuário com o PAT2Math incluirá sempre, no mínimo, os termos e condições apresentados neste documento. Tais termos são denominados "Termos Universais".';
terms_ptBR[1][3] = '1.3. O contrato do usuário com o PAT2Math também incluirá os termos de quaisquer Notificações Legais aplicáveis aos Serviços, além dos Termos Universais. Todos esses termos são referidos a seguir como "Termos Adicionais". Nos casos em que forem aplicáveis Termos Adicionais a um Serviço, tais termos estarão disponíveis para leitura por parte do usuário nesse Serviço ou por meio do uso do mesmo.';
terms_ptBR[1][4] = '1.4. Os Termos Universais, juntamente com os Termos Adicionais, formam um acordo com efeito jurídico entre o usuário e o PAT2Math relativamente ao uso dos Serviços por parte do usuário. É importante que o usuário os leiam com atenção. Coletivamente, este contrato é denominado "Termos".';
terms_ptBR[1][5] = '1.5. No caso de haver alguma contradição entre o que indicam os Termos Adicionais e o que indicam os Termos Universais, deverão prevalecer os Termos Adicionais em relação a esse Serviço.';

terms_ptBR[2][0] = '2. Aceitação dos Termos';
terms_ptBR[2][1] = '2.1. Para usar os Serviços, o usuário deverá primeiro concordar com os Termos. Não é permitido o uso dos Serviços por parte do usuário se ele não aceitar os Termos.';
terms_ptBR[2][2] = '2.2. O usuário pode aceitar os Termos: (A) clicando para aceitar ou concordar com os Termos, no caso de essa opção ser disponibilizada pelo PAT2Math na interface do usuário para qualquer Serviço; ou (B) usando efetivamente os Serviços. Nesse caso, o usuário compreende e aceita que o PAT2Math considerará o seu uso dos Serviços uma aceitação dos Termos a partir desse momento.';
terms_ptBR[2][3] = '2.3. O usuário não poderá usar os Serviços nem aceitar os Termos se: (a) não tiver idade legal para celebrar um acordo com efeito jurídico com o PAT2Math; ou (b) for uma pessoa com restrições quanto ao recebimento de serviços impostas pelas leis do Brasil ou de outros países, incluindo o país onde o usuário é residente ou a partir do qual usa os Serviços.';
terms_ptBR[2][4] = '2.4. Antes de continuar, o usuário deverá imprimir ou guardar uma cópia local dos Termos Universais em seus registros.';
	
terms_ptBR[3][0] = '3. Prestação dos Serviços pelo PAT2Math';
terms_ptBR[3][1] = '3.1. O PAT2Math está constantemente se inovando para poder oferecer a melhor experiência possível aos seus usuários. O usuário tem conhecimento e aceita que a forma e natureza dos Serviços fornecidos pelo PAT2Math podem mudar ocasionalmente sem aviso prévio ao usuário.';
terms_ptBR[3][2] = '3.2. Como parte dessa constante inovação, o usuário tem conhecimento e concorda que o PAT2Math pode, a seu próprio critério, deixar (permanente ou temporariamente) de fornecer os Serviços (ou qualquer funcionalidade dos Serviços) aos usuários em geral, sem aviso prévio. O usuário pode deixar de utilizar os Serviços a qualquer momento. O usuário não necessita informar especificamente o PAT2Math quando deixar de usar os Serviços.';
terms_ptBR[3][3] = '3.3. O usuário reconhece e aceita que, se o PAT2Math desativar a sua conta, poderá ser impedido de acessar os Serviços, os detalhes da conta ou quaisquer arquivos ou outros conteúdos que estejam na conta.';
	
terms_ptBR[4][0] = '4. Uso dos Serviços por parte do usuário';
terms_ptBR[4][1] = '4.1. Para acessar determinados Serviços, poderá ser solicitado ao usuário que forneça informações pessoais (tais como identificação ou detalhes de contato em redes sociais como Facebook, LinkedIn, entre outras) como parte do processo de registro para o Serviço ou como parte da utilização continuada dos Serviços por parte do usuário. O usuário concorda que as informações de registro que fornecer ao PAT2Math serão sempre exatas, corretas e atualizadas.';
terms_ptBR[4][2] = '4.2. O usuário concorda em usar os Serviços somente para os fins permitidos: (a) pelos Termos; e (b) quaisquer leis, regulamentos ou práticas ou diretrizes geralmente aceitas nas jurisdições relevantes (inclusive todas as leis em relação à exportação de dados ou software para e do Brasil ou outros países relevantes).';
terms_ptBR[4][3] = '4.3. O usuário concorda em não acessar (nem tentar acessar) qualquer um dos Serviços por qualquer meio que não seja através da interface fornecida pelo PAT2Math, exceto se for especificamente autorizado a tal em um contrato em separado firmado com o PAT2Math. O usuário concorda especificamente em não acessar (nem tentar acessar) qualquer um dos Serviços através de meios automatizados (inclusive uso de scripts ou rastreadores da web), bem como deverá garantir que esteja em conformidade com as instruções definidas em todos os arquivos *.txt apresentados nos Serviços.';
terms_ptBR[4][4] = '4.4. O usuário concorda em não participar de nenhuma atividade que interfira ou interrompa o funcionamento dos Serviços (ou servidores e redes conectados aos Serviços).';
terms_ptBR[4][5] = '4.5. Exceto se tiver sido especificamente autorizado por meio de um contrato em separado firmado com o PAT2Math, o usuário concorda em não reproduzir, duplicar, copiar, vender, comercializar ou revender os Serviços para qualquer efeito.';
terms_ptBR[4][6] = '4.6. O usuário concorda que será o único responsável (e que o PAT2Math não tem qualquer responsabilidade perante o usuário ou terceiros) por qualquer não cumprimento das suas obrigações no que diz respeito aos Termos e pelas consequências (incluindo qualquer perda ou dano que o PAT2Math possa sofrer) resultantes desse não cumprimento.';

terms_ptBR[5][0] = '5. Segurança da conta e senhas do usuário';
terms_ptBR[5][1] = '5.1. O usuário concorda e compreende que será responsável por manter a confidencialidade das senhas associadas a qualquer conta que utilize para acessar os Serviços.';
terms_ptBR[5][2] = '5.2. Dessa forma, o usuário concorda que será o único responsável perante o PAT2Math por todas as atividades que ocorram na respectiva conta.';
terms_ptBR[5][3] = '5.3. Se tomar conhecimento de qualquer utilização não autorizada da sua senha ou da sua conta, o usuário concorda em notificar imediatamente o PAT2Math em pat2math@gmail.com.';
	
terms_ptBR[6][0] = '6. Conteúdo nos Serviços';
terms_ptBR[6][1] = '6.1. O usuário compreende que a responsabilidade integral por todas as informações (tais como arquivos de dados, texto escrito, software de computador, música, arquivos de áudio ou outros sons, fotografias, vídeos ou outras imagens) a que possa ter acesso como parte dos Serviços, ou através da utilização dos mesmos, é da pessoa que deu origem a esse conteúdo. Todas essas informações são denominadas "Conteúdo".';
terms_ptBR[6][2] = '6.2. O usuário deverá estar ciente de que o Conteúdo que lhe é apresentado como parte dos Serviços, incluindo, sem limitação, anúncios nos Serviços e Conteúdo patrocinado nos Serviços, pode estar protegido por direitos de propriedade intelectual que são de propriedade dos patrocinadores, anunciantes ou parceiros que fornecem esse Conteúdo ao PAT2Math (ou por outras pessoas ou empresas em seu nome). O usuário não poderá efetuar modificação, aluguel, arrendamento, empréstimo, venda, distribuição ou criação de obras derivadas baseadas neste Conteúdo (no todo ou em parte), a menos que tenha sido especificamente autorizado a fazê-lo, através de um contrato em separado, pelo PAT2Math ou pelos proprietários desse Conteúdo.';
terms_ptBR[6][3] = '6.3. O PAT2Math se reserva o direito (mas não tem qualquer obrigação) de pré-selecionar, rever, marcar, filtrar, modificar, recusar ou remover qualquer ou todo Conteúdo de qualquer Serviço. Para alguns dos Serviços, o PAT2Math pode fornecer ferramentas para filtrar conteúdos sexuais explícitos.';
terms_ptBR[6][4] = '6.4. O usuário compreende que, ao utilizar os Serviços, pode estar exposto a Conteúdo que possa considerar ofensivo, indecente ou censurável e que, a este respeito, utiliza os Serviços por sua conta e risco.';
terms_ptBR[6][5] = '6.5. O usuário concorda que será o único responsável (e que o PAT2Math não tem qualquer responsabilidade perante o usuário ou terceiros) por qualquer Conteúdo que crie, transmita ou visualize enquanto utiliza os Serviços e pelas consequências das suas ações (incluindo qualquer perda ou dano que o PAT2Math possa sofrer) resultantes disso.';
			
terms_ptBR[7][0] = '7. Direitos de propriedade';
terms_ptBR[7][1] = '7.1. O usuário reconhece e concorda que o PAT2Math (ou os licenciadores do PAT2Math) detém todos os direitos legais, títulos e participações relativas aos Serviços, incluindo quaisquer direitos de propriedade intelectual que subsistam nos Serviços (quer esses direitos estejam registrados ou não, e em qualquer parte do mundo onde esses direitos possam existir). Além disso, o usuário reconhece que os Serviços podem conter informações designadas confidenciais pelo PAT2Math e que não as revelará sem o prévio consentimento escrito do PAT2Math.';
terms_ptBR[7][2] = '7.2. A menos que o usuário tenha concordado por escrito em contrário com o PAT2Math, nada nos Termos lhe dá o direito de utilizar qualquer uma das marcas registradas, marcas comerciais, marcas de serviços, logotipos, nomes de domínios e outras características de marca especiais do PAT2Math.';
terms_ptBR[7][3] = '7.3. Se lhe tiver sido concedido um direito explícito de utilização de qualquer uma dessas características de marca através de um contrato escrito em separado celebrado com o PAT2Math, o usuário concorda que o uso dessas características será feito de acordo com esse contrato, com quaisquer cláusulas aplicáveis dos Termos e com as diretrizes de uso das características de marca do PAT2Math, conforme possam ser atualizadas periodicamente.';
terms_ptBR[7][4] = '7.4. À exceção da licença limitada referida na Seção 1.1, o PAT2Math reconhece e aceita que não obtém qualquer direito, título ou participação do usuário (ou dos seus licenciadores) de acordo com estes Termos relativamente a qualquer Conteúdo que o usuário possa enviar, publicar, transmitir ou apresentar nos Serviços ou através deles, incluindo quaisquer direitos de propriedade intelectual que subsistam nesse Conteúdo (quer esses direitos estejam registrados ou não, e em qualquer parte do mundo onde esses direitos possam existir). A menos que tenha acordado por escrito de outra forma com o PAT2Math, o usuário concorda que é responsável por proteger e aplicar esses direitos e que o PAT2Math não tem qualquer obrigação de fazê-lo em seu nome.';
terms_ptBR[7][5] = '7.5. O usuário concorda que não removerá, ocultará, nem alterará quaisquer avisos de direitos de propriedade (incluindo avisos de direitos de autor e de marcas comerciais) que possam estar afixados ou contidos nos Serviços.';
terms_ptBR[7][6] = '7.6. A menos que tenha sido expressamente autorizado por escrito pelo PAT2Math a fazê-lo, o usuário concorda que, ao usar os Serviços, não irá utilizar qualquer marca comercial, marca de serviço, marca registrada, logotipo de qualquer empresa ou organização de forma que seja provável ou pretendido que cause confusão relativamente ao proprietário ou usuário autorizado dessas marcas, nomes ou logotipos.';
	
terms_ptBR[8][0] = '8. Licença do PAT2Math';
terms_ptBR[8][1] = '8.1. O PAT2Math concede ao usuário uma licença pessoal, internacional, isenta de royalties, não atribuível e não exclusiva para utilizar o software fornecido ao usuário pelo PAT2Math como parte dos serviços fornecidos ao usuário pelo PAT2Math (denominado "Software" a seguir). Essa licença tem como único objetivo permitir o uso, por parte do usuário, dos benefícios dos Serviços tal como são fornecidos pelo PAT2Math, da forma permitida pelos Termos.';
terms_ptBR[8][2] = '8.2. O usuário não poderá (nem poderá permitir a mais ninguém) copiar, modificar, criar uma obra derivada de, realizar engenharia inversa, descompilar ou, de qualquer outro modo, tentar extrair o código-fonte do Software ou de qualquer parte que o componha, a menos que seja expressamente permitido ou previsto por lei, ou que o usuário tenha sido especificamente autorizado a fazê-lo pelo PAT2Math, por escrito.';
terms_ptBR[8][3] = '8.3. A menos que o PAT2Math lhe tenha concedido uma permissão específica, por escrito, para fazê-lo, o usuário não poderá atribuir (ou conceder uma sublicença de) seus direitos de utilização do Software, conceder uma garantia relativa aos seus direitos de utilização do Software ou, de qualquer outro modo, transferir qualquer parte dos seus direitos de utilização do Software.';
terms_ptBR[8][4] = '8.4. O PAT2Math se reserva o direito de excluir o histórico de uso do usuário, quando esse não tiver mais acessado o sistema por 3 meses.';

terms_ptBR[9][0] = '9. Licença de conteúdo do usuário';
terms_ptBR[9][1] = '9.1. O usuário retém direitos autorais e quaisquer outros direitos que já tiver posse em relação ao Conteúdo que enviar, publicar ou exibir nos Serviços ou através deles. Ao enviar, publicar ou exibir conteúdo, o usuário concede ao PAT2Math uma licença irrevogável, perpétua, mundial, isenta de royalties e não exclusiva de reproduzir, adaptar, modificar, traduzir, publicar, distribuir publicamente, exibir publicamente e distribuir qualquer Conteúdo que o usuário enviar, publicar ou exibir nos Serviços ou através deles. Essa licença tem como único objetivo permitir ao PAT2Math apresentar, distribuir e promover os Serviços e pode ser revogada para certos Serviços, conforme definido nos Termos Adicionais desses Serviços.';
terms_ptBR[9][2] = '9.2. O usuário concorda que essa licença inclui o direito do PAT2Math de disponibilizar esse Conteúdo a outras empresas, organizações ou indivíduos com quem o PAT2Math tenha relações para o fornecimento de serviços licenciados e para o uso desse Conteúdo relacionado ao fornecimento desses serviços.';
terms_ptBR[9][3] = '9.3. O usuário compreende que o PAT2Math, ao efetuar as etapas técnicas necessárias para fornecer os Serviços aos nossos usuários, pode (a) transmitir ou distribuir o seu Conteúdo por várias redes públicas e em várias mídias de dados; e (b) efetuar as alterações necessárias ao Conteúdo do usuário para ajustar e adaptar esse Conteúdo aos requisitos técnicos de conexão de redes, dispositivos, serviços ou mídia. O usuário concorda que essa licença permitirá ao PAT2Math realizar tais ações.';
terms_ptBR[9][4] = '9.4. O usuário confirma e garante ao PAT2Math que tem todos os direitos, poderes e autoridade necessários para outorgar a licença citada anteriormente.';

terms_ptBR[10][0] = '10. Atualizações de software';
terms_ptBR[10][1] = '10.1. O Software usado pelo usuário pode, ocasionalmente, fazer download e instalar automaticamente atualizações do PAT2Math. Essas atualizações são concebidas para melhorar, aperfeiçoar e desenvolver os Serviços e podem ser apresentadas sob a forma de correções de erros, funções aprimoradas, novos módulos de software e versões completamente novas. O usuário concorda em receber essas atualizações (e permitir que o PAT2Math lhe forneça) como parte da utilização dos Serviços.';

terms_ptBR[11][0] = '11. Término da relação do usuário com o PAT2Math';
terms_ptBR[11][1] = '11.1. Os Termos continuarão a ser aplicáveis até serem encerrados pelo usuário ou pelo PAT2Math, conforme estabelecido a seguir.';
terms_ptBR[11][2] = '11.2. Se o usuário quiser encerrar o seu contrato com o PAT2Math, pode fazê-lo (a) notificando o PAT2Math a qualquer momento e (b) encerrando as contas relativas a todos os Serviços que utiliza, no caso de essa opção ser disponibilizada pelo PAT2Math. A notificação deverá ser enviada pelo usuário, por escrito, para o endereço do PAT2Math indicado no início destes Termos.';
terms_ptBR[11][3] = '11.3. O PAT2Math pode, a qualquer momento, encerrar o contrato com o usuário se: (A) o usuário tiver violado qualquer cláusula dos Termos (ou tiver agido de forma que claramente mostre que não pretende ou não pode cumprir as cláusulas dos Termos); ou (B) tal for exigido ao PAT2Math por lei (por exemplo, quando o fornecimento dos Serviços ao usuário for ou se tornar ilegal); ou (C) o parceiro com o qual o PAT2Math ofereceu os Serviços ao usuário tiver encerrado a sua relação com o PAT2Math ou tiver deixado de oferecer os Serviços ao usuário; ou (D) o PAT2Math estiver em fase de transição para uma situação em que já não fornece os Serviços aos usuários do país no qual o usuário é residente ou a partir do qual utiliza os Serviços; ou (E) o fornecimento dos Serviços ao usuário pelo PAT2Math já não for, na opinião do PAT2Math, comercialmente viável. (F) o usuário deixar de acessar o sistema por 3 meses.';
terms_ptBR[11][4] = '11.4. Nada nesta Seção afetará os direitos do PAT2Math relativos ao fornecimento de Serviços de acordo com a Seção 3 dos Termos.';
terms_ptBR[11][5] = '11.5. Quando estes Termos forem encerrados, todos os direitos, obrigações e responsabilidades de que o usuário ou o PAT2Math tenham se beneficiado, tenham sido sujeitos a (ou que tenham acumulado enquanto os Termos tiverem estado em vigor) ou que expressamente devam continuar em vigor indefinidamente não serão afetados por essa resolução, e as cláusulas do parágrafo 18.6 continuarão a ser aplicáveis a esses direitos, obrigações e responsabilidades indefinidamente.';

terms_ptBR[12][0] = '12. EXCLUSÃO DE GARANTIAS';
terms_ptBR[12][1] = '12.1. NADA NESTES TERMOS, INCLUSIVE AS SEÇÕES 12 E 13, EXCLUIRÁ OU LIMITARÁ A RESPONSABILIDADE OU GARANTIA DO PAT2MATH POR PERDAS QUE NÃO POSSAM SER LEGALMENTE EXCLUÍDAS OU LIMITADAS PELA LEI APLICÁVEL. ALGUMAS JURISDIÇÕES NÃO PERMITEM A EXCLUSÃO DE CERTAS GARANTIAS OU CONDIÇÕES OU A LIMITAÇÃO OU EXCLUSÃO DE RESPONSABILIDADE POR PERDA OU DANO CAUSADOS POR NEGLIGÊNCIA, QUEBRA DE CONTRATO OU QUEBRA DOS TERMOS IMPLÍCITOS, OU DANOS INCIDENTAIS E CONSEQUENCIAIS. CONSEQUENTEMENTE, APENAS AS LIMITAÇÕES QUE FOREM PERMITIDAS POR LEI NA SUA JURISDIÇÃO SE APLICARÃO AO USUÁRIO, E A NOSSA RESPONSABILIDADE LIMITADA AO MÁXIMO PERMITIDO POR LEI.';
terms_ptBR[12][2] = '12.2. O USUÁRIO ENTENDE E CONCORDA EXPRESSAMENTE QUE O USO DOS SERVIÇOS É POR CONTA E RISCO DO USUÁRIO E QUE OS SERVIÇOS SÃO FORNECIDOS "NA FORMA EM QUE SE ENCONTRAM" E "DE ACORDO COM A DISPONIBILIDADE".';
terms_ptBR[12][3] = '12.3. ESPECIFICAMENTE, O PAT2MATH, AS SUAS SUBSIDIÁRIAS E AFILIADAS E LICENCIADORES NÃO GARANTEM QUE: (A) O USO DOS SERVIÇOS ATENDERÁ AOS REQUISITOS DO USUÁRIO; (B) O USO DOS SERVIÇOS SERÁ ININTERRUPTO, PONTUAL, SEGURO E ISENTO DE ERROS; (C) QUALQUER INFORMAÇÃO OBTIDA PELO USUÁRIO EM DECORRÊNCIA DO SEU USO DOS SERVIÇOS SERÁ PRECISA OU CONFIÁVEL; E (D) OS DEFEITOS NO FUNCIONAMENTO OU NA FUNCIONALIDADE DE QUALQUER SOFTWARE FORNECIDO AO USUÁRIO COMO PARTE DOS SERVIÇOS SERÃO CORRIGIDOS.';
terms_ptBR[12][4] = '12.4. QUALQUER MATERIAL BAIXADO OU OBTIDO DE OUTRA FORMA POR MEIO DOS SERVIÇOS É OBTIDO A SEU PRÓPRIO CRITÉRIO E RISCO, E QUE O USUÁRIO SERÁ O ÚNICO RESPONSÁVEL POR QUALQUER DANO AO SISTEMA DO SEU COMPUTADOR OU QUALQUER OUTRO APARELHO, OU PELA PERDA DE DADOS QUE ACONTEÇA COMO RESULTADO DO DOWNLOAD DE QUALQUER MATERIAL.';
terms_ptBR[12][5] = '12.5. NENHUM CONSELHO OU INFORMAÇÃO, SEJA ORAL OU ESCRITO, OBTIDO PELO USUÁRIO DO PAT2MATH, DOS SERVIÇOS OU POR MEIO DESSES, CRIARÁ QUALQUER GARANTIA QUE NÃO ESTEJA EXPRESSAMENTE DECLARADA NOS TERMOS.';
terms_ptBR[12][6] = '12.6. O PAT2MATH AINDA EXPRESSAMENTE SE ISENTA DE TODAS AS RESPONSABILIDADES, GARANTIAS OU CONDIÇÕES DE QUALQUER NATUREZA, SEJAM EXPRESSAS OU IMPLÍCITAS, INCLUINDO, ENTRE OUTROS, GARANTIAS IMPLÍCITAS E AS CONDIÇÕES DE MERCADO, A ADAPTAÇÃO PARA UM PROPÓSITO PARTICULAR E O NÃO-INFRINGIMENTO.';

terms_ptBR[13][0] = '13. LIMITAÇÃO DE RESPONSABILIDADE';
terms_ptBR[13][1] = '13.1. SUJEITO À CLÁUSULA GERAL MENCIONADA NO PARÁGRAFO 12.1 ACIMA, O USUÁRIO ENTENDE E CONCORDA QUE O PAT2MATH, AS SUAS SUBSIDIÁRIAS E AFILIADAS E RESPECTIVOS LICENCIADORES E PARCEIROS NÃO SERÃO RESPONSÁVEIS PERANTE O USUÁRIO POR: (A) QUAISQUER DANOS DIRETOS, INDIRETOS, INCIDENTAIS, ESPECIAIS, CONSEQUENCIAIS OU EXEMPLARES, INCORRIDOS PELO USUÁRIO, CAUSADOS E SOB QUALQUER TEORIA DE RESPONSABILIDADE. ISSO INCLUIRÁ, MAS NÃO SE LIMITARÁ A, QUALQUER PERDA DE LUCROS (INCORRIDA DIRETA OU INDIRETAMENTE), QUALQUER PERDA RELACIONADA COM A BOA-FÉ OU REPUTAÇÃO COMERCIAL, QUALQUER PERDA DE DADOS QUE O USUÁRIO POSSA SOFRER, CUSTOS DE AQUISIÇÃO DE BENS OU SERVIÇOS OU OUTRA PERDA INTANGÍVEL; (B) QUALQUER PERDA OU DANO EM QUE O USUÁRIO POSSA INCORRER, INCLUSIVE, MAS NÃO SE LIMITANDO A, PERDA OU DANOS EM DECORRÊNCIA DE: a. QUALQUER EXPECTATIVA DO USUÁRIO QUANTO À INTEGRIDADE, PRECISÃO OU EXISTÊNCIA DE QUALQUER PUBLICIDADE, OU EM RESULTADO DE QUALQUER RELAÇÃO OU TRANSAÇÃO REALIZADA COM QUALQUER ANUNCIANTE, PATROCINADOR OU PARCEIRO CUJA PUBLICIDADE APAREÇA NOS SERVIÇOS; b. QUAISQUER ALTERAÇÕES QUE O PAT2MATH POSSA FAZER AOS SERVIÇOS, OU POR QUALQUER CESSAÇÃO PERMANENTE OU TEMPORÁRIA DO FORNECIMENTO DOS SERVIÇOS (OU QUAISQUER FUNCIONALIDADES NOS PRÓPRIOS SERVIÇOS); c. A ELIMINAÇÃO, CORRUPÇÃO OU INCAPACIDADE DE ARMAZENAMENTO DE QUALQUER CONTEÚDO OU OUTROS DADOS DE COMUNICAÇÕES MANTIDOS OU TRANSMITIDOS POR OU ATRAVÉS DA UTILIZAÇÃO DOS SERVIÇOS POR PARTE DO USUÁRIO; d. O NÃO FORNECIMENTO AO PAT2MATH, POR PARTE DO USUÁRIO, DE INFORMAÇÕES CORRETAS RELATIVAS À CONTA; e. A NÃO MANUTENÇÃO, POR PARTE DO USUÁRIO, DA SEGURANÇA E DA CONFIDENCIALIDADE DOS DETALHES DA SUA CONTA E SENHA.';
terms_ptBR[13][2] = '13.2. AS LIMITAÇÕES DE RESPONSABILIDADE DO PAT2MATH PERANTE O USUÁRIO, MENCIONADAS NO PARÁGRAFO 13.1 ACIMA, SERÃO APLICÁVEIS INDEPENDENTEMENTE DE O PAT2MATH TER OU NÃO SIDO NOTIFICADO OU AINDA QUE O USUÁRIO DEVESSE TER CONHECIMENTO DA POSSIBILIDADE DE OCORRÊNCIA DE TAIS PERDAS.';

terms_ptBR[14][0] = '14. Políticas relativas a direitos autorais e marcas comerciais';
terms_ptBR[14][1] = '14.1. É política do PAT2Math responder a avisos sobre supostas infrações de direitos autorais, conforme a lei internacional aplicável sobre propriedade intelectual, bem como encerrar as contas de infratores reincidentes.';

terms_ptBR[15][0] = '15. Anúncios';
terms_ptBR[15][1] = '15.1. Alguns dos Serviços são mantidos por receita proveniente de publicidade e podem exibir anúncios e promoções. Tais anúncios podem ser contextuais ao conteúdo da informação armazenada nos Serviços, pesquisas feitas por meio dos Serviços ou outras informações.';
terms_ptBR[15][2] = '15.2. A maneira, modo e abrangência da publicidade do PAT2Math nos Serviços estão sujeitos a alterações sem aviso prévio específico ao usuário.';
terms_ptBR[15][3] = '15.3. Considerando a concessão por parte do PAT2Math do acesso e uso dos Serviços, o usuário manifesta o seu acordo sobre a possibilidade de o PAT2Math colocar tais anúncios nos Serviços.';

terms_ptBR[16][0] = '16. Outros conteúdos';
terms_ptBR[16][1] = '16.1. Os Serviços podem incluir hiperlinks a outros sites, conteúdo ou recursos da web. O PAT2Math pode não ter nenhum controle sobre quaisquer sites ou recursos da web fornecidos por empresas ou pessoas que não o PAT2Math.';
terms_ptBR[16][2] = '16.2. O usuário reconhece e concorda que o PAT2Math não é responsável pela disponibilidade de qualquer um desses sites ou recursos externos e nem endossa qualquer anúncio, produto ou outro material disponível ou originado em tais sites e recursos da web.';
terms_ptBR[16][3] = '16.3. O usuário reconhece e concorda que o PAT2Math não é responsável por qualquer perda ou dano em que possa incorrer em resultado da disponibilidade de tais sites ou recursos externos, ou em decorrência de qualquer expectativa esperada pelo usuário em relação à integridade, precisão ou existência de quaisquer anúncios, produtos ou outros materiais presentes ou disponíveis a partir de tais sites ou recursos da web.';

terms_ptBR[17][0] = '17. Alterações nos Termos';
terms_ptBR[17][1] = '17.1. O PAT2Math poderá alterar periodicamente os Termos Universais ou Termos Adicionais.';
terms_ptBR[17][2] = '17.2. O usuário compreende e concorda que, se utilizar os Serviços após a data de alteração dos Termos Universais ou Termos Adicionais, o PAT2Math considerará essa utilização como uma aceitação dos Termos Universais ou Termos Adicionais atualizados.';

terms_ptBR[18][0] = '18. Termos jurídicos gerais';
terms_ptBR[18][1] = '18.1. Ocasionalmente, durante a utilização dos Serviços, o usuário poderá (em resultado da ou através da utilização dos Serviços) usar um serviço, fazer download de um componente de software ou comprar bens fornecidos por outra pessoa ou empresa. A utilização de tais serviços, software ou bens por parte do usuário poderá estar sujeita a termos em separado entre o usuário e a empresa ou pessoa em questão. Nesse caso, os Termos não afetam a relação jurídica do usuário com essas empresas ou indivíduos.';
terms_ptBR[18][2] = '18.2. Os Termos constituem o contrato integral entre o usuário e o PAT2Math e regulam a utilização dos Serviços (excluindo quaisquer serviços que possam eventualmente ser fornecidos pelo PAT2Math de acordo com um contrato escrito em separado), substituindo na íntegra quaisquer contratos anteriores estabelecidos entre o usuário e o PAT2Math em relação aos Serviços.';
terms_ptBR[18][3] = '18.3. O usuário concorda que o PAT2Math poderá lhe enviar avisos, incluindo aqueles sobre alterações feitas aos Termos, por e-mail, carta ou publicações nos Serviços.';
terms_ptBR[18][4] = '18.4. O usuário concorda que, se o PAT2Math não exercer ou utilizar qualquer direito legal ou direito reconhecido contido nos Termos (ou ao qual o PAT2Math tenha direito nos termos de qualquer lei aplicável), isso não será considerado como uma renúncia formal aos direitos do PAT2Math, mantendo-se tais direitos disponíveis para todos os devidos efeitos.';
terms_ptBR[18][5] = '18.5. Se qualquer tribunal, tendo jurisdição para decidir sobre essa questão, determinar que qualquer cláusula destes Termos é inválida, tal cláusula será removida dos Termos sem afetar a validade do restante dos Termos. As cláusulas restantes dos Termos continuarão sendo válidas e aplicáveis.';
terms_ptBR[18][6] = '18.6. Os Termos, e o relacionamento entre o usuário e o PAT2Math conforme os Termos, serão regidos pelas leis do Estado do Rio Grande do Sul, independentemente do conflito de cláusulas legais. O usuário e o PAT2Math concordam em submeter à exclusiva jurisdição dos tribunais localizados na Cidade de São Leopoldo, Rio Grande do Sul, a resolução de quaisquer questões legais resultantes dos Termos. Não obstante o referido, o usuário concorda que o PAT2Math poderá ainda apresentar medidas injuntivas (ou de tipo equivalente de compensação legal urgente) em qualquer jurisdição.';
