var terms_esES = new Array(19);

for(var i = 0; i < 19; i++)
	terms_esES[i] = new Array();


terms_esES[0][0] = "Terminos de Uso";
terms_esES[0][1] = "Por favor, lea con atención los términos de uso:";
terms_esES[0][2] = "Términos de Servicio del PAT2Math:";
terms_esES[0][3] = "volver";

terms_esES[1][0] = '1. Relación del usuario con el PAT2Math';
terms_esES[1][1] = '1.1. El uso de productos, software, servicios y sitios web de PAT2Math (denominados colectivamente "Servicios" en este documento y excluyendo cualquier servicio proporcionado por el usuario por PAT2Math de acuerdo con un contrato por escrito separado) por parte del usuario está sujeto a los términos de un contrato entre el usuario y el PAT2Math. "PAT2Math" significa "Personal Affective Tutor to Math" (Tutor individual afectivo para matemáticas) y está siendo desarrollado por un equipo de investigadores en Inteligencia Artificial aplicada a la Educación del Programa Interdisciplinario de Postgrado en Computación Aplicada de UNISINOS, en São Leopoldo, bajo la coordinación de la Profa. Patricia A. Jaques Maillard. Este documento explica cómo se constituye el contrato y presenta sus términos.';
terms_esES[1][2] = '1.2. Excepto si se acuerda de otra manera por escrito por el PAT2Math, el contrato del usuario con el PAT2Math incluirá siempre, como mínimo, los términos y condiciones presentados en este documento. Tales términos se denominan "Términos Universales".';
terms_esES[1][3] = '1.3. El contrato del usuario con PAT2Math también incluirá los términos de cualquier notificación legal aplicable a los servicios, además de los términos universales. Todos estos términos se mencionan a continuación como "Términos Adicionales". En los casos en que se aplican las condiciones adicionales a un servicio, estos términos estarán disponibles para su lectura por parte del usuario en dicho Servicio o por el uso del mismo.';
terms_esES[1][4] = '1.4. Los Términos Universales, junto con los Términos Adicional, forman un acuerdo con efecto jurídico entre el usuario y el PAT2Math respecto al uso de los Servicios por parte del usuario. Es importante que el usuario los lea con atención. Colectivamente, este contrato se denomina "Términos".';
terms_esES[1][5] = '1.5. En caso de que haya alguna contradicción entre lo que indican los Términos Adicional y lo que indican los Términos Universales, prevalecerán los Términos Adicional en relación a ese Servicio.';

terms_esES[2][0] = '2. Aceptación de los Términos';
terms_esES[2][1] = '2.1. Para utilizar los Servicios, el usuario deberá primero acordar los Términos. No se permite el uso de los Servicios por parte del usuario si no acepta los Términos.';
terms_esES[2][2] = '2.2. El usuario puede aceptar los Términos: (A) haciendo clic para aceptar o acordar los Términos, en el caso de que esta opción esté disponible por PAT2Math en la interfaz de usuario para cualquier Servicio; o (B) utilizando efectivamente los Servicios. En ese caso, el usuario entiende y acepta que el PAT2Math considerará su uso de los Servicios una aceptación de los Términos a partir de ese momento.';
terms_esES[2][3] = '2.3. El usuario no podrá usar los Servicios ni aceptar los Términos si: (a) no tiene edad legal para celebrar un acuerdo con efecto jurídico con el PAT2Math; o (b) es una persona con restricciones en cuanto a la recepción de servicios impuestas por las leyes de Brasil o de otros países, incluyendo el país donde el usuario es residente o desde el que usa los Servicios.';
terms_esES[2][4] = '2.4. Antes de continuar, el usuario deberá imprimir o guardar una copia local de los Términos Universales en sus registros.';

terms_esES[3][0] = '3. Prestación de los Servicios por PAT2Math';
terms_esES[3][1] = '3.1. PAT2Math está constantemente innovando para poder ofrecer la mejor experiencia posible a sus usuarios. El usuario tiene conocimiento y acepta que la forma y naturaleza de los Servicios proporcionados por PAT2Math pueden cambiar de vez en cuando sin previo aviso al usuario.';
terms_esES[3][2] = '3.2. Como parte de esta constante innovación, el usuario tiene conocimiento y está de acuerdo en que el PAT2Math puede, a su propio criterio, dejar (permanente o temporalmente) de proporcionar los Servicios (o cualquier funcionalidad de los Servicios) a los usuarios en general, sin previo aviso. El usuario puede dejar de utilizar los Servicios en cualquier momento. El usuario no necesita informar específicamente a PAT2Math cuando deje de usar los Servicios.';
terms_esES[3][3] = '3.3. El usuario reconoce y acepta que si el PAT2Math deshabilita su cuenta, puede que no pueda acceder a los Servicios, los detalles de la cuenta o cualquier archivo u otro contenido que esté en la cuenta.';

terms_esES[4][0] = '4. Uso de los Servicios por parte del usuario';
terms_esES[4][1] = '4.1. Para acceder a determinados servicios, se le puede pedir al usuario que proporcione información personal (como identificación o detalles de contacto en redes sociales como Facebook, LinkedIn, entre otras) como parte del proceso de registro del Servicio o como parte del uso continuado de los Servicios por parte del usuario. El usuario acepta que la información de registro que proporcione al PAT2Math será siempre exacta, correcta y actualizada.';
terms_esES[4][2] = '4.2. El usuario acepta utilizar los Servicios únicamente para los fines permitidos: (a) por los Términos; y (b) cualesquiera leyes, reglamentos o prácticas o directrices generalmente aceptadas en las jurisdicciones relevantes (incluyendo todas las leyes en relación a la exportación de datos o software para y de Brasil u otros países relevantes).';
terms_esES[4][3] = '4.3. El usuario acuerda no acceder (ni intentar acceder) a cualquiera de los Servicios por cualquier medio que no sea a través de la interfaz proporcionada por PAT2Math, a menos que esté específicamente autorizado a ello en un contrato por separado firmado con PAT2Math. El usuario acuerda específicamente no acceder (ni intentar acceder) a cualquiera de los Servicios a través de medios automatizados (incluyendo el uso de scripts o rastreadores web), así como asegurarse de que cumple con las instrucciones definidas en todos los archivos *.txt presentados en los Servicios.';
terms_esES[4][4] = '4.4. El usuario acuerda no participar en ninguna actividad que interfiera o interrumpe el funcionamiento de los Servicios (o servidores y redes conectados a los Servicios).';
terms_esES[4][5] = '4.5. Excepto si ha sido específicamente autorizado por medio de un contrato por separado firmado con PAT2Math, el usuario acuerda no reproducir, duplicar, copiar, vender, comercializar o revender los Servicios para cualquier efecto.';
terms_esES[4][6] = '4.6. El usuario acepta que será el único responsable (y que el PAT2Math no tiene ninguna responsabilidad ante el usuario o terceros) por cualquier incumplimiento de sus obligaciones en lo que se refiere a los Términos y las consecuencias (incluyendo cualquier pérdida o daño que el PAT2Math pueda sufrir) resultantes de dicho incumplimiento.';

terms_esES[5][0] = '5. Seguridad de la cuenta y contraseñas del usuario';
terms_esES[5][1] = '5.1. El usuario acepta y comprende que será responsable de mantener la confidencialidad de las contraseñas asociadas a cualquier cuenta que utilice para acceder a los Servicios.';
terms_esES[5][2] = '5.2. De esta forma, el usuario acepta que será el único responsable ante el PAT2Math por todas las actividades que ocurran en su cuenta.';
terms_esES[5][3] = '5.3. Si conoce cualquier uso no autorizado de su contraseña o de su cuenta, el usuario acuerda notificar inmediatamente PAT2Math en pat2math@gmail.com.';

terms_esES[6][0] = '6. Contenido en los Servicios';
terms_esES[6][1] = '6.1. El usuario entiende que la responsabilidad integral por toda la información (tales como archivos de datos, texto escrito, software de computadora, música, archivos de audio u otros sonidos, fotografías, vídeos u otras imágenes) a que pueda tener acceso como parte de los Servicios, oa través de la utilización de los mismos, es de la persona que dio origen a ese contenido. Todas estas informaciones se denominan "Contenido".';
terms_esES[6][2] = '6.2. El usuario debe ser consciente de que el Contenido que se le presenta como parte de los Servicios, incluyendo, sin limitación, los anuncios en los Servicios y el Contenido patrocinado en los Servicios, puede estar protegido por derechos de propiedad intelectual que son propiedad de los patrocinadores, anunciantes o socios que suministren ese Contenido a PAT2Math (o por otras personas o empresas en su nombre). El usuario no podrá efectuar modificaciones, alquiler, arrendamiento, préstamo, venta, distribución o creación de obras derivadas basadas en este Contenido (en su totalidad o en parte), a menos que haya sido específicamente autorizado a hacerlo a través de un contrato por separado por el PAT2Math o por los propietarios de dicho Contenido.';
terms_esES[6][3] = '6.3. PAT2Math se reserva el derecho (pero no tiene ninguna obligación) de preseleccionar, revisar, marcar, filtrar, modificar, rechazar o eliminar cualquier Contenido de cualquier Servicio. Para algunos de los Servicios, el PAT2Math puede proporcionar herramientas para filtrar contenidos sexuales explícitos.';
terms_esES[6][4] = '6.4. El usuario entiende que, al utilizar los Servicios, puede estar expuesto a Contenido que pueda considerar ofensivo, indecente o censurable y que, a este respecto, utiliza los Servicios por su cuenta y riesgo.';
terms_esES[6][5] = '6.5. El usuario acepta que será el único responsable (y que el PAT2Math no tiene ninguna responsabilidad ante el usuario o terceros) por cualquier Contenido que cree, transmita o visualice mientras utiliza los Servicios y las consecuencias de sus acciones (incluyendo cualquier pérdida o daño que el PAT2Math pueda sufrir) resultantes de ello.';

terms_esES[7][0] = '7. Derechos de propiedad';
terms_esES[7][1] = '7.1. El usuario reconoce y acepta que PAT2Math (o los licenciatarios de PAT2Math) poseen todos los derechos legales, títulos y participaciones relativos a los Servicios, incluyendo cualquier derecho de propiedad intelectual que subsista en los Servicios (ya sea que dichos derechos estén registrados o no, y en cualquier parte del mundo donde esos derechos puedan existir). Además, el usuario reconoce que los Servicios pueden contener información designada confidencial por PAT2Math y que no las revelará sin el previo consentimiento escrito del PAT2Math.';
terms_esES[7][2] = '7.2. A menos que el usuario haya aceptado por escrito en contrario con el PAT2Math, nada en los Términos le da el derecho de utilizar cualquiera de las marcas registradas, marcas comerciales, marcas de servicios, logotipos, nombres de dominio y otras características de marca especiales del PAT2Math.';
terms_esES[7][3] = '7.3. Si se le ha concedido un derecho explícito de utilizar cualquiera de estas características de marca mediante un contrato escrito por separado celebrado con PAT2Math, el usuario acepta que el uso de estas características se hará de acuerdo con dicho contrato, con cualquier cláusula aplicables de los Términos y con las directrices de uso de las características de marca del PAT2Math, conforme puedan ser actualizadas periódicamente.';
terms_esES[7][4] = '7.4. A excepción de la licencia limitada mencionada en la Sección 1.1, el PAT2Math reconoce y acepta que no obtiene ningún derecho, título o participación del usuario (o de sus licenciatarios) de acuerdo con estos Términos para cualquier Contenido que el usuario pueda enviar, publicar , transmitir o presentar en los Servicios oa través de ellos, incluyendo cualquier derecho de propiedad intelectual que subsista en ese Contenido (ya sea que estos derechos estén registrados o no, y en cualquier parte del mundo donde dichos derechos puedan existir). A menos que haya acordado por escrito de otra forma con el PAT2Math, usted acepta que es responsable de proteger y aplicar estos derechos y que el PAT2Math no tiene ninguna obligación de hacerlo en su nombre.';
terms_esES[7][5] = '7.5. El usuario acepta que no quita, ocultará ni alterará ningún aviso de derechos de propiedad (incluyendo avisos de derechos de autor y marcas comerciales) que puedan estar fijados o contenidos en los Servicios.';
terms_esES[7][6] = '7.6. A menos que haya sido expresamente autorizado por escrito por el PAT2Math a hacerlo, el usuario acepta que, al usar los Servicios, no utilizará ninguna marca comercial, marca de servicio, marca registrada, logotipo de cualquier empresa u organización de forma que sea probable o previsto que cause confusión con el propietario o el usuario autorizado de dichas marcas, nombres o logotipos.';

terms_esES[8][0] = '8. Licencia de PAT2Math';
terms_esES[8][1] = '8.1. PAT2Math otorga al usuario una licencia personal, internacional, libre de regalías, no atribuible y no exclusiva para utilizar el software proporcionado al usuario por PAT2Math como parte de los servicios proporcionados al usuario por el PAT2Math (denominado "Software" a continuación). Esta licencia tiene como único objetivo permitir el uso por parte del usuario de los beneficios de los Servicios tal como son proporcionados por PAT2Math, de la forma permitida por los Términos.';
terms_esES[8][2] = '8.2. El usuario no podrá (ni podrá permitir a nadie más) copiar, modificar, crear una obra derivada de, realizar ingeniería inversa, descompilar o, de cualquier otro modo, intentar extraer el código fuente del Software o de cualquier parte que el mismo a menos que esté expresamente permitido o previsto por la ley, o que el usuario haya sido específicamente autorizado a hacerlo por PAT2Math, por escrito.';
terms_esES[8][3] = '8.3. A menos que el PAT2Math le haya concedido un permiso específico, por escrito, para hacerlo, el usuario no podrá asignar (o conceder una sublicencia de) sus derechos de uso del Software, conceder una garantía relativa a sus derechos de uso del Software o de cualquier otro modo transferir cualquier parte de sus derechos de uso del Software.';
terms_esES[8][4] = '8.4. PAT2Math se reserva el derecho de excluir el historial de uso del usuario, cuando éste ya no haya accedido al sistema durante 3 meses.';

terms_esES[9][0] = '9. Licencia de contenido del usuario';
terms_esES[9][1] = '9.1. El usuario retiene derechos de autor y cualquier otro derecho que ya tenga posesión con respecto al Contenido que envíe, publique o muestre en los Servicios oa través de ellos. Al enviar, publicar o exhibir contenido, el usuario concede al PAT2Math una licencia irrevocable, perpetua, mundial, exenta de royalties y no exclusiva de reproducir, adaptar, modificar, traducir, publicar, distribuir públicamente, exhibir públicamente y distribuir cualquier Contenido que el usuario enviar, publicar o exhibir en los Servicios oa través de ellos. Esta licencia tiene como único objetivo permitir al PAT2Math presentar, distribuir y promover los Servicios y puede ser revocada para ciertos Servicios, tal como se define en los Términos Adicional de estos Servicios.';
terms_esES[9][2] = '9.2. El usuario acepta que esta licencia incluye el derecho del PAT2Math de poner a disposición ese Contenido a otras empresas, organizaciones o individuos con quienes el PAT2Math tenga relaciones para la provisión de servicios licenciados y para el uso de ese Contenido relacionado con la provisión de dichos servicios.';
terms_esES[9][3] = '9.3. El usuario comprende que el PAT2Math, al efectuar las etapas técnicas necesarias para proporcionar los Servicios a nuestros usuarios, puede (a) transmitir o distribuir su Contenido por varias redes públicas y en varios medios de datos; y (b) realizar los cambios necesarios en el Contenido del usuario para ajustar y adaptar dicho Contenido a los requisitos técnicos de conexión de redes, dispositivos, servicios o medios. El usuario acepta que esta licencia permitirá al PAT2Math realizar tales acciones.';
terms_esES[9][4] = '9.4. El usuario confirma y garantiza al PAT2Math que tiene todos los derechos, poderes y autoridad necesarios para otorgar la licencia citada anteriormente.';

terms_esES[10][0] = '10. Actualizaciones de software';
terms_esES[10][1] = '10.1. El software utilizado por el usuario puede ocasionalmente descargar e instalar automáticamente actualizaciones de PAT2Math. Estas actualizaciones están diseñadas para mejorar, perfeccionar y desarrollar los servicios y se pueden presentar en forma de correcciones de errores, funciones mejoradas, nuevos módulos de software y versiones completamente nuevas. El usuario acepta recibir estas actualizaciones (y permitir que el PAT2Math le proporcione) como parte de la utilización de los Servicios.';

terms_esES[11][0] = '11. Fin de la relación del usuario con el PAT2Math';
terms_esES[11][1] = '11.1. Los Términos seguirán siendo aplicables hasta que sean cerrados por el usuario o por el PAT2Math, según se establece a continuación.';
terms_esES[11][2] = '11.2. Si el usuario desea cerrar su contrato con PAT2Math, puede hacerlo notificando a PAT2Math en cualquier momento y (b) cerrando las cuentas relativas a todos los Servicios que utilice, en caso de que esta opción esté disponible por PAT2Math. La notificación deberá ser enviada por el usuario por escrito a la dirección de PAT2Math indicada al principio de estos Términos.';
terms_esES[11][3] = '11.3. PAT2Math puede, en cualquier momento, cerrar el contrato con el usuario si: (A) el usuario ha violado cualquier cláusula de los Términos (o ha actuado de forma que claramente muestre que no desea o no puede cumplir las cláusulas de los Términos); o (B) se exige al PAT2Math por ley (por ejemplo, cuando el suministro de los Servicios al usuario sea o se haga ilegal); o (C) el socio con el cual el PAT2Math ofreció los Servicios al usuario ha cerrado su relación con el PAT2Math o ha dejado de ofrecer los Servicios al usuario; o (D) PAT2Math está en fase de transición a una situación en la que ya no proporciona los Servicios a los usuarios del país en el que el usuario es residente o desde el que utiliza los Servicios; o (E) el suministro de los Servicios al usuario por el PAT2Math ya no es, en opinión del PAT2Math, comercialmente viable. (F) el usuario deja de acceder al sistema durante 3 meses.';
terms_esES[11][4] = '11.4. Nada en esta Sección afectará los derechos de PAT2Math relativos al suministro de servicios de acuerdo con la Sección 3 de los Términos.';
terms_esES[11][5] = '11.5. Cuando se hayan finalizado estos Términos, todos los derechos, obligaciones y responsabilidades que el usuario o el PAT2Math se hayan beneficiado, hayan sido (o que hayan acumulado mientras los Términos hayan estado en vigor) o que expresamente deban continuar en vigor indefinidamente no serán afectados por esta resolución, y las cláusulas del párrafo 18.6 seguirán siendo aplicables a esos derechos, obligaciones y responsabilidades indefinidamente.';

terms_esES[12][0] = '12. EXCLUSIÓN DE LAS GARANTÍAS';
terms_esES[12][1] = '12.1. NADA EN ESTOS TÉRMINOS, INCLUYENDO LAS SECCIONES 12 Y 13, EXCLUIRÁ O LIMITARÁ LA RESPONSABILIDAD O GARANTÍA DEL PAT2MATH POR PÉRDIDAS QUE NO PUEDEN SER LEGALMENTE EXCLUIDAS O LIMITADAS POR LA LEY APLICABLE. ALGUNAS JURISDICIONES NO PERMITEN LA EXCLUSIÓN DE DETERMINADAS GARANTÍAS O CONDICIONES O LIMITACIÓN O EXCLUSIÓN DE RESPONSABILIDAD POR PÉRDIDA O DAÑO CAUSADOS POR NEGLIGENCIA, QUEBRA DE CONTRATO O QUEBRA DE LOS TÉRMINOS IMPLÍCITOS, O DAÑOS INCIDENTALES Y CONSECUENCIAL. CONSECUENTE, SOLAMENTE LAS LIMITACIONES QUE PERMITEN POR LA LEY EN SU JURISDICCIÓN SE APLICARÁ AL USUARIO, Y NUESTRA RESPONSABILIDAD LIMITADA AL MÁXIMA PERMITIDO POR LEY.';
terms_esES[12][2] = '12.2. EL USUARIO ENTIENDE Y ACEPTA EXPRESAMENTE QUE EL USO DE LOS SERVICIOS ES POR CUENTA Y RIESGO DEL USUARIO Y QUE LOS SERVICIOS SE SUMINISTRADOS "EN LA FORMA EN QUE SE ENCUENTRAN" Y "DE ACUERDO CON LA DISPONIBILIDAD".';
terms_esES[12][3] = '12.3. ESPECIALMENTE, PAT2MATH, SUS SUBSIDIARIAS Y AFILIADAS Y LICENCIANTES NO GARANTIZAN QUE: (A) EL USO DE LOS SERVICIOS ATENDERÁ LOS REQUISITOS DEL USUARIO; (B) EL USO DE LOS SERVICIOS SERÁ ININTERRUMPIDO, PUNTUAL, SEGURO e ISENTO DE ERRORES; (C) CUALQUIER INFORMACIÓN OBTENIDA POR EL USUARIO EN LA DECORACIÓN DE SU USO DE LOS SERVICIOS SERÁ NECESITA O CONFIABLE; Y (D) LOS DEFECTOS EN EL FUNCIONAMIENTO O EN LA FUNCIONALIDAD DE CUALQUIER SOFTWARE SUMINISTRADO AL USUARIO COMO PARTE DE LOS SERVICIOS SERÁ CORREGIDOS.';
terms_esES[12][4] = '12.4. CUALQUIER MATERIAL BAJADO O OBTENIDO DE OTRA FORMA POR MEDIO DE LOS SERVICIOS ES OBTENIDO A SU PROPIO CRITERIO Y RIESGO, Y QUE EL USUARIO SERÁ EL ÚNICO RESPONSABLE POR CUALQUIER DAÑO AL SISTEMA DE SU COMPUTADORA O CUALQUIER OTRO APARATO, O POR LA PÉRDIDA DE DATOS QUE ACONECE COMO RESULTADO DE LA DESCARGA DE CUALQUIER MATERIAL.';
terms_esES[12][5] = '12.5. NINGÚN CONSEJO O INFORMACIÓN, SEA ORAL O ESCRITO, OBTENIDO POR EL USUARIO DEL PAT2MATH, DE LOS SERVICIOS O POR MEDIO DE, CREARÁ CUALQUIER GARANTÍA QUE NO ESTÉ EXPRESAMENTE DECLARADA EN LOS TÉRMINOS.';
terms_esES[12][6] = '12.6. PAT2MATH EXPRESAMENTE EXPRESAMENTE DE TODAS LAS RESPONSABILIDADES, GARANTÍAS O CONDICIONES DE CUALQUIER NATURALEZA, SEA EXPRESAS O IMPLÍCITAS, INCLUYENDO, ENTRE OTROS, GARANTÍAS IMPLÍCITAS Y LAS CONDICIONES DE MERCADO, LA ADAPTACIÓN PARA UN PROPÓSITO PARTICULAR Y EL NO INFRINGIMIENTO.';

terms_esES[13][0] = '13. LIMITACIÓN DE RESPONSABILIDAD';
terms_esES[13][1] = '13.1. SUJETO A LA CLÁUSULA GENERAL MENCIONADA EN EL PÁRRAFO 12.1 ANTERIOR, EL USUARIO ENTIENDE Y ACEPTA que PAT2MATH, SUS SUBSIDIARIAS Y AFILIADAS Y SUS RESPECTIVOS LICENCIADORES Y SOCIOS NO SERÁ RESPONSABLES ANTE EL USUARIO POR: (A) CUALQUIER DAÑO DIRECTO, INDIRECTO, INCIDENTAL, ESPECIAL, CONSECUENCIALES O EJEMPLARES, INCORRIDOS POR EL USUARIO, CAUSADOS Y BAJO CUALQUIER TEORÍA DE RESPONSABILIDAD. ESO INCLUIRÁ, PERO NO LIMITARÁ A, CUALQUIER PÉRDIDA DE BENEFICIOS (INCORRIDA DIRECTA O INDIRECTAMENTE), CUALQUIER PÉRDIDA RELACIONADA CON LA BUENA FE o LA REPUESTACIÓN COMERCIAL, CUALQUIER PÉRDIDA DE DATOS QUE EL USUARIO PUEDE SUFRIR, COSTOS DE ADQUISICIÓN DE BIENES O SERVICIOS O OTRA PÉRDIDA INTANGIBLE; (B) CUALQUIER PÉRDIDA O DAÑO EN EL QUE EL USUARIO PUEDE INCORRER, INCLUYENDO, PERO NO LIMITADO A, PÉRDIDA O DAÑOS EN DECORACIÓN DE: a. CUALQUIER EXPECTATIVA DEL USUARIO POR LA INTEGRIDAD, PRECISIÓN O EXISTENCIA DE CUALQUIER PUBLICIDAD, O RESULTADO DE CUALQUIER RELACIÓN O TRANSACCIÓN REALIZADA CON CUALQUIER ANUNCIANTE, PATROCINADOR O PARCIAL CUYA PUBLICIDAD APAREZCA EN LOS SERVICIOS; b. CUALQUIER CAMBIO QUE PAT2MATH PUEDA HACER A LOS SERVICIOS, O POR CUALQUIER CESE PERMANENTE O TEMPORAL DEL SUMINISTRO DE LOS SERVICIOS (O CUALQUIER FUNCIONALIDAD EN LOS PROPIOS SERVICIOS); c. ELIMINACIÓN, CORRECCIÓN O INCAPACIDAD DE ALMACENAMIENTO DE CUALQUIER CONTENIDO O DE OTROS DATOS DE COMUNICACIONES MANTIDOS O TRANSMITIDOS POR O A TRAVÉS DE LA UTILIZACIÓN DE LOS SERVICIOS POR PARTE DEL USUARIO; d. EL NO SUMINISTRO AL PAT2MATH, POR PARTE DEL USUARIO, DE INFORMACIÓN CORRECTA RELATIVA A LA CUENTA; e. A NO MANTENIMIENTO, POR PARTE DEL USUARIO, LA SEGURIDAD Y LA CONFIDENCIALIDAD DE LOS DETALLES DE SU CUENTA Y CONTRASEÑA.';
terms_esES[13][2] = '13.2. LAS LIMITACIONES DE RESPONSABILIDAD DEL PAT2MATH ANTE EL USUARIO, MENCIONADAS EN EL PÁRRAFO 13.1 ARRIBA, SERÁN APLICABLES INDIVIDENTEMENTE DE PAT2MATH TER O NO SIDO NOTIFICADO O INCLUSO QUE DEBE TENER CONOCIMIENTO DE LA POSIBILIDAD DE O CURRENCIA DE ESTAS PÉRDIDAS.';

terms_esES[14][0] = '14. Políticas de derechos de autor y marcas comerciales';
terms_esES[14][1] = '14.1. Es política de PAT2Math responder a advertencias sobre supuestas infracciones de derechos de autor, conforme a la ley internacional aplicable sobre propiedad intelectual, así como cerrar las cuentas de infractores reincidentes.';

terms_esES[15][0] = '15. Anuncios';
terms_esES[15][1] = '15.1. Algunos de los servicios se mantienen por ingresos procedentes de publicidad y pueden mostrar anuncios y promociones. Tales anuncios pueden ser contextuales al contenido de la información almacenada en los Servicios, investigaciones realizadas a través de los Servicios u otra información.';
terms_esES[15][2] = '15.2. La forma, el modo y el alcance de la publicidad de PAT2Math en los Servicios están sujetos a cambios sin previo aviso específico al usuario.';
terms_esES[15][3] = '15.3. Considerando la concesión por parte del PAT2Math del acceso y uso de los Servicios, el usuario manifiesta su acuerdo sobre la posibilidad de que el PAT2Math coloque dichos anuncios en los Servicios.';

terms_esES[16][0] = '16. Otros contenidos';
terms_esES[16][1] = '16.1. Los Servicios pueden incluir hipervínculos a otros sitios, contenido o recursos web. PAT2Math puede no tener ningún control sobre los sitios web o los recursos proporcionados por empresas o personas que no sean PAT2Math.';
terms_esES[16][2] = '16.2. El usuario reconoce y acepta que PAT2Math no es responsable de la disponibilidad de cualquiera de estos sitios o recursos externos y no endosa cualquier anuncio, producto u otro material disponible o originado en dichos sitios y recursos web.';
terms_esES[16][3] = '16.3. El usuario reconoce y acepta que PAT2Math no es responsable de cualquier pérdida o daño en el que pueda incurrir como resultado de la disponibilidad de tales sitios o recursos externos, o como consecuencia de cualquier expectativa esperada por el usuario en cuanto a la integridad, precisión o existencia de cualesquiera anuncios, productos u otros materiales presentes o disponibles a partir de tales sitios o recursos de la web.';

terms_esES[17][0] = '17. Cambios en los Términos';
terms_esES[17][1] = '17.1. PAT2Math podrá modificar periódicamente los Términos y Condiciones de Uso del Usuario.';
terms_esES[17][2] = '17.2. El usuario entiende y acepta que, si utiliza los Servicios después de la fecha de modificación de los Términos Universales o de las Condiciones Adicionales, el PAT2Math considerará esta utilización como una aceptación de los Términos de Uso o de las Condiciones Adicionales actualizadas.';

terms_esES[18][0] = '18. Términos jurídicos generales';
terms_esES[18][1] = '18.1. Ocasionalmente, durante la utilización de los Servicios, el usuario puede (a causa de o mediante el uso de los Servicios) utilizar un servicio, descargar un componente de software o comprar bienes proporcionados por otra persona o empresa. La utilización de tales servicios, software o bienes por parte del usuario puede estar sujeta a términos por separado entre el usuario y la empresa o la persona en cuestión. En este caso, los Términos no afectan a la relación jurídica del usuario con dichas empresas o individuos.';
terms_esES[18][2] = '18.2. Los Términos constituyen el contrato íntegro entre el usuario y el PAT2Math y regulan la utilización de los Servicios (excluyendo cualquier servicio que puedan ser proporcionados por PAT2Math de acuerdo con un contrato escrito por separado), sustituyendo en su totalidad cualquier contrato anterior establecido entre el usuario y el usuario el PAT2Math en relación a los Servicios.';
terms_esES[18][3] = '18.3. Usted acepta que PAT2Math le enviará avisos, incluyendo aquellos sobre cambios realizados a los Términos, por e-mail, carta o publicaciones en los Servicios.';
terms_esES[18][4] = '18.4. El usuario acepta que si el PAT2Math no ejerce o utiliza ningún derecho legal o derecho reconocido contenido en los Términos (o al que el PAT2Math tenga derecho en virtud de cualquier ley aplicable), esto no será considerado como una renuncia formal a los derechos del PAT2Math, manteniéndose tales derechos disponibles para todos los efectos.';
terms_esES[18][5] = '18.5. Si cualquier tribunal, teniendo jurisdicción para decidir sobre esta cuestión, determina que cualquier cláusula de estos Términos es inválida, dicha cláusula se eliminará de los Términos sin afectar la validez del resto de los Términos. Las cláusulas restantes de los Términos continuarán siendo válidas y aplicables.';
terms_esES[18][6] = '18.6. Los Términos, y la relación entre el usuario y el PAT2Math conforme a los Términos, serán regidos por las leyes del Estado de Rio Grande do Sul, independientemente del conflicto de cláusulas legales. El usuario y el PAT2Math acuerdan someter a la exclusiva jurisdicción de los tribunales ubicados en la Ciudad de São Leopoldo, Rio Grande del Sur, la resolución de cualesquiera cuestiones legales resultantes de los Términos. A pesar de lo dicho, el usuario acepta que el PAT2Math podrá aún presentar medidas injuntivas (o de tipo equivalente de compensación legal urgente) en cualquier jurisdicción.';
